In [1]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import re

In [2]:
with open("../data/CUADv1.json") as f:
    data = json.load(f)

test = pd.DataFrame.from_records(data)

test.info()

<class 'pandas.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   data     510 non-null    object
 1   version  510 non-null    str
dtypes: object(1), str(1)
memory usage: 8.1+ KB

In [3]:
test.describe()

                                                     data   version
count                                                 510       510
unique                                                510         1
top     {'title': 'LIMEENERGYCO_09_09_1999-EX-10-DISTR...  aok_v1.0
freq                                                    1       510

In [5]:
with open("../data/all_v1.json") as f:
    tos_data = json.load(f)

tos_df = pd.DataFrame(tos_data.values())
tos_df.head()

,doc,id,original_text,reference_summary,title,uid,case_code,case_text,note,title_code,title_text,urls,tldr_code,tldr_text
0,Pokemon GO Terms of Service,5786730a6cca83a54c0035b7,welcome to the pokémon go video game services ...,hi.,,legalsum01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Pokemon GO Terms of Service,57866df76cca83a54c0035a1,by using our services you are agreeing to thes...,by playing this game you agree to these terms....,Agreement To Terms,legalsum02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Pokemon GO Terms of Service,5786730a6cca83a54c0035b6,if you want to use certain features of the ser...,you have to use google pokemon trainer club or...,Eligibility and Account Registration,legalsum03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Pokemon GO Terms of Service,57866df76cca83a54c0035a0,during game play please be aware of your surro...,don t die or hurt others and if you do it s no...,Safe Play,legalsum04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pokemon GO Terms of Service,57866df76cca83a54c00359f,subject to your compliance with these terms ni...,don t copy modify resell distribute or reverse...,Rights in App,legalsum05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
tos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   doc                446 non-null    str
 1   id                 85 non-null     str
 2   original_text      446 non-null    str
 3   reference_summary  446 non-null    str
 4   title              85 non-null     str
 5   uid                446 non-null    str
 6   case_code          117 non-null    str
 7   case_text          117 non-null    str
 8   note               361 non-null    str
 9   title_code         352 non-null    str
 10  title_text         352 non-null    str
 11  urls               361 non-null    str
 12  tldr_code          101 non-null    str
 13  tldr_text          101 non-null    str
dtypes: str(14)
memory usage: 48.9 KB

In [11]:
tos_df = tos_df[["doc", "original_text", "reference_summary"]]
tos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   doc                446 non-null    str
 1   original_text      446 non-null    str
 2   reference_summary  446 non-null    str
dtypes: str(3)
memory usage: 10.6 KB

In [12]:
tos_df["summary_word_count"] = tos_df["reference_summary"].str.split().str.len()
tos_df.sort_values("summary_word_count").head(15)

,doc,original_text,reference_summary,summary_word_count
0,Pokemon GO Terms of Service,welcome to the pokémon go video game services ...,hi.,1
52,Android SDK License Agreement (June 2014),you agree that you will not engage in any acti...,no malware.,2
358,Privacy Policy,github uses cookies to make interactions with ...,github requires cookies.,3
393,Privacy Statement,cookies are small data files that are commonly...,cookies are required.,3
60,Android SDK License Agreement (June 2014),export restrictions. the sdk is subject to uni...,export restrictions apply.,3
144,Terms of Service,your payments to the site are nonrefundable.,no refund policy.,3
419,Cookie Policy,we use cookies if you have a facebook account ...,facebook uses cookies.,3
18,Pokemon GO Terms of Service,if you have any questions about these terms or...,termsofservice nianticlabs com.,3
68,"Google Play Game Services (May 15th, 2013)",the indemnification provision in section 9 of ...,don t blame google.,4
45,YouTube Terms of Service,13. assignmentthese terms of service and any r...,the jurisdiction is california.,4
96,Privacy Policy,you do not have to provide any personal data t...,no need to register.,4
59,Android SDK License Agreement (June 2014),to the maximum extent permitted by law you agr...,don t blame google.,4
323,Terms of Use,you forever waive and agree not to claim or as...,sign away moral rights.,4
111,Terms and Conditions of Use,if you do not want to continue to be charged o...,spotify doesn t provide refunds.,5
47,Android SDK License Agreement (June 2014),you agree that you will not take any actions t...,don t fork the sdk.,5

In [24]:
import os
tos_df.to_csv("../data/tos_for_review.csv", index=False)
os.getcwd()

'/home/daniel/Legal-text-simplifier/notebooks'

In [33]:
df2 = pd.read_csv("../data/tos_for_review.csv")
df2.head()
len(df2)

444